### ISSUE TITLE
PPC not available anymore

### ISSUE THREAD

**Issue by stefaanbolle** [philippe44/LMS-to-uPnP#12]
What is the reason that the PPC build has been removed in 0.2.7.3-dev-3?
Can this be made back available in a next build?
This would be much appreciated.

**Comment by philippe44** [comment]
I just thought that nobody was using it and I also thought, that because PPC are big endian processors, a lot of features would not work (I don't have any platform to test), so I removed it

**Comment by stefaanbolle** [comment]
Any chance to have it back?
Would be appreciated

**Comment by philippe44** [comment]
It's back now - so, it was working for you ?
