### ISSUE TITLE
Players listed with wrong IP

### ISSUE THREAD

**Issue by TokTias** [philippe44/LMS-to-uPnP#13]
Hi !

Your neat plugin finds all my seven UPnP players, but they are all listed (in the Player tab) with the same (and wrong) IP address; 169.254.29.250.

The log is repeating the following two messages in chunks : 
[16-02-19 21:31:57.0778] Slim::Networking::Discovery::Players::_players_error (146) Unable to get players: Timed out waiting for data
[16-02-19 21:31:59.6131] Slim::Networking::SqueezeNetwork::Players::_players_error (334) Unable to get players from SN: Connect timed out: Bad file descriptor, retrying in 604800 seconds

(It seems to be trigged when my Domoticz server is polling the Logitech Media server for its detected devices (`?))

FYI: My UPnP players are all different Philips devices :

- MCi900H
- NP3900
- NP3700
- NP3300
- NP2900
- NP2500
- AW3000

Cheers & TIA !
/T

**Comment by philippe44** [comment]
Can you post a log of squeeze2upnp itself ? A link to it can be found in LMS settings, advanced, then select "UPnP/DLNA Bridge"

**Comment by TokTias** [comment]
Hi !
The Log is attached.
[upnpbridge-log.log.txt](https://github.com/philippe44/LMS-to-uPnP/files/139167/upnpbridge-log.log.txt)

**Comment by philippe44** [comment]
169.254.29.250 is the address of your LMS server, as it is discovered. This is not the address of the players. This is aself-assigned address, so how do you assign an address to your server ? And if you know its address, you can set it in the Bridge parameters

**Comment by philippe44** [comment]
Hi - without further feedback from you, I'll close the ticket
