### ISSUE TITLE
Volume problem on Pure One Flow

### ISSUE THREAD

**Issue by DamianoCroci** [philippe44/LMS-to-uPnP#14]
Setting codecs to Mp3 only it works perfectly but the volume doesn't work. Tried with all the possible combination on Player volume management. The volume works without any issue using other normal DLNA applications.
Do you have any link for a donation ? I like your work very much and want to contribute.

Damiano

**Comment by philippe44** [comment]
A log taken when changing volume would help, as well as a copy of your configuration file (both can be found in the plugin settings). Thank you for the intention of donation, but I cannot accept any

**Comment by DamianoCroci** [comment]
Hi Philippe, thanks for your answer.
Attached the log and config file.

   best regards
[upnpbridge.damiano.zip](https://github.com/philippe44/LMS-to-uPnP/files/154621/upnpbridge.damiano.zip)

**Comment by philippe44** [comment]
The PureFlow is refusing the volume command. If you have a windows machine, can you download this http://www.meshcommander.com/upnptools and laucnh "device spy". The PureFlow should appear in the list, expand the tree and go under "urn:schamas-upnp-org:service:RenderingControl", open it and you should see a "SetVolume" command. Double click on it and tell me what you see in the drop-down list of "channel"

**Comment by DamianoCroci** [comment]
In the drop-down list there is only a 'Master' channel.
BTW, using the ui2 parameter invoking the SetVolume method I can change the volume on the One Flow. See screenshot attached
![setvolume](https://cloud.githubusercontent.com/assets/17552652/13555983/45b9ac3c-e3cf-11e5-8f91-8780fe519b20.png)

**Comment by philippe44** [comment]
Thanks - I'm starting to see what's happening. The URL used to control the volume, which is detected when the device is discovered, seems to be wrong. Could you set, in the upnpbridge.xml configuration file, set \<main_log> to sdebug (not debug, but sdebug), start the bridge, play something and do a few failed volume and send me the log (must be very verbose)

**Comment by DamianoCroci** [comment]
see attached
[upnpbridge-log.zip](https://github.com/philippe44/LMS-to-uPnP/files/160523/upnpbridge-log.zip)

**Comment by philippe44** [comment]
I think the log you set is the slimmain_log, not the main_log

**Comment by DamianoCroci** [comment]
Attache the log and the configuration file so you can check if I missed something for the log setting.
Let me if correct now
[upnpbridge_one_flow.zip](https://github.com/philippe44/LMS-to-uPnP/files/161374/upnpbridge_one_flow.zip)

**Comment by philippe44** [comment]
I don't understand why the correct information does not show up in the log, but what I've done is a special version that forces the log. Obviously, the URL for controling the volume is wrong, but I want to see what's happening when I'm collecting it, at player discovery. Could you replace the version by this one ?
[squeeze2upnp-x86.zip](https://github.com/philippe44/LMS-to-uPnP/files/161865/squeeze2upnp-x86.zip)

**Comment by DamianoCroci** [comment]
See attached
[upnpbridge_one_flow070316.zip](https://github.com/philippe44/LMS-to-uPnP/files/161921/upnpbridge_one_flow070316.zip)

**Comment by philippe44** [comment]
Thanks ! almost there. So it confirms that the service to control the volume is not found. Normally, I look for 3 services
"urn:schemas-upnp-org:service:AVTransport:1"
"urn:schemas-upnp-org:service:RenderingControl:1" ==> this one is missing
"urn:schemas-upnp-org:service:ConnectionManager:1"
Could you do a printscreen on what you see in the DeviceSpy screen when you expand the tree under the OneFlow and have these 3 services listed ? This is probably where there is a problem

**Comment by DamianoCroci** [comment]
See Attached
[upnp_screenshots.zip](https://github.com/philippe44/LMS-to-uPnP/files/162762/upnp_screenshots.zip)

**Comment by DamianoCroci** [comment]
In order to make a new test and send the log I should be at home, I'll let you know

**Comment by DamianoCroci** [comment]
OK, I got the log file.
[upnpbridge_log_080316.zip](https://github.com/philippe44/LMS-to-uPnP/files/163213/upnpbridge_log_080316.zip)

**Comment by DamianoCroci** [comment]
Just look to differences between the One Flow as seen directly and proxied.
![shot4](https://cloud.githubusercontent.com/assets/17552652/13610516/54e61962-e55e-11e5-9ff9-04c195324310.JPG)
![shot5](https://cloud.githubusercontent.com/assets/17552652/13610515/54e5782c-e55e-11e5-87ed-fba5ef8cdaa4.JPG)

**Comment by philippe44** [comment]
okay - I got it now. I don't know why, but as you can see, the OneFlow is claiming version 3 for the RenderingControl namespace and I only accept 1. I need to see how to change that

**Comment by philippe44** [comment]
Should be fixed in 0.2.7.3-dev-8. I had to change a few tricky things that might impact all users. Hope they won't throw tomatoes at me :-)

**Comment by DamianoCroci** [comment]
Perfect! I works now! I haven't noticed any other issue at the moment. In case I let you know.
Thanks for the suberb support.

  best regards

Damiano

**Comment by philippe44** [comment]
you're welcome
