### ISSUE TITLE
uPNP transition / stucked after reconnect with Sonos

### ISSUE THREAD

**Issue by SteveBurg** [philippe44/LMS-to-uPnP#15]
Hi Philippe,

since the December dev releases i have problems with Devices after reconnecting again to squeeze2upnp (especially Sonos). You can reproduce this with pulling out the power cable while 
1. streaming to an internet radio station -> logfile (1), removing renderer looks good.
2. Powering on again, device is found -> logfile (2), looks also good
3. Playing the same Radio Station, just by pressing play on LMS leads into a "File opened twice" or into an endless uPNP transition / uPNP stop and the player doesn't respond anymore. Only restarting squeeze2upnp helps in that case.
See logfile
[upnp_error_steve.txt](https://github.com/philippe44/LMS-to-uPnP/files/157589/upnp_error_steve.txt)

Hope you get an idea ;)
Thanks in advance.
Steve

**Comment by philippe44** [comment]
Can you tell me what version you're using and what platform ? (I was not able to reproduce that on 2.7.3-dev-6 and Windows). When you unplug the Sonos, is it playing or do you stop it in LMS first, then unplug it ? Can you also post your config file.

**Comment by SteveBurg** [comment]
Thanks for your fast answer ;)
That happens using 2.7.3-dev-6 on linux debian. When unplugging Sonos i do nothing before, it's in streaming state. Config (which is grown with many settings since month/releases) is attached.
[squeeze2upnp_config.txt](https://github.com/philippe44/LMS-to-uPnP/files/158428/squeeze2upnp_config.txt)

**Comment by philippe44** [comment]
I've found and corrected what's likely to be the cause. It's in dev-7

**Comment by SteveBurg** [comment]
Yes, great - that fixed it! Thanks
