### ISSUE TITLE
WebOpen:111 No context

### ISSUE THREAD

**Issue by SteveBurg** [philippe44/LMS-to-uPnP#16]
Hi Philippe,
saw it on different systems in two different scenarios (debian):
(1. when switching between radio stations i got a non responding sonos without any chance to use it anymore before a restart of squeeze2upnp

(2. after the sonos connected again, same no context message and no chance to use it. Only after the next restart of sq2upnp. Will investigate more details behind it.
[squeeze2upnp.log.txt](https://github.com/philippe44/LMS-to-uPnP/files/174699/squeeze2upnp.log.txt)

**Comment by philippe44** [comment]
The "no context" upon reconnection is not a problem as such, it's expected on some players upon restart of squeeze2upnp. The non responding Sonos is an issue of course. What version are you using. I corrected an issue on that exact topci 2 days ago in 0.2.7.3-dev-12

**Comment by SteveBurg** [comment]
It happened yesterday and today after installing the latest dev-12 version. For the switching of radio stations (where the non responding occured) i saw sometimes the "opened twice" message as we saw before the linux calculation of the locking time fix

**Comment by philippe44** [comment]
okay - just to make sure I got the test setup right, can you send me the configuration parameters you used for that Sonos player ?

**Comment by SteveBurg** [comment]
yes - sure. here is the whole config. And as info: when taking a deeper look into LMS log, i see that this is happening when LMS writes: "Metadata provider Slim::Plugin::RadioTime::Metadata::provider failed" or the requested TuneIN URL is not reachable. Hope, that helps.
[squeeze2upnp_config.txt](https://github.com/philippe44/LMS-to-uPnP/files/174892/squeeze2upnp_config.txt)

**Comment by philippe44** [comment]
I did not see anything strange in the config. Do you think you could take a complete log of what happens when its fails ? I've tried on my Sonos to change from radio to radio multiple time w/o a problem. Could you alos tell me maybe what are the URL you are using ?

**Comment by SteveBurg** [comment]
tested again and again, but removed aac streams and have no faulty handling anymore. Will watch at it the next days and give you feedback. (Closing issue so long)
