### ISSUE TITLE
Problem with spotify protocol handler

### ISSUE THREAD

**Issue by mrfloppy82** [philippe44/LMS-to-uPnP#18]
Hello,

today i switched to spotify. I use the offical LMS Plugin and the spotify protocol Handler. When I switch to the next song it plays for a few seconds and then the song stops playing on the upnp client but the lms web interface
shows that the song plays. I have only the Problem when i switch to an other song. I have a Yamaha rx-v475.

Regards
Nico

**Comment by mrfloppy82** [comment]
I Have the same Problem with my Panasonic Bluray Player Panasonic DMP-BDT174EG. I Think this is an general Problem between the bridge and the protocol handler. With squeezelite I have no problems skipping songs from spotify,

**Comment by philippe44** [comment]
Does this happen with local tracks? I don't use stopify so it might be better that you go on the logitech forum and get help from there
