### ISSUE TITLE
Incorrect volume calculation for Pioneer AVR (negative volume values)

### ISSUE THREAD

**Issue by guny74** [philippe44/LMS-to-uPnP#26]
Hello,

first thank for your work, I helps to build a selfmade multiroom system....

I tried to use it with an Pioneer Avr SC-2022 as an DNLN Client. Connecting and playing music
works fors fine, but the volume control does not work.
Looking at the volume calculation coding explains it....(if I understand it right)

The Problem is, that the Pioneer and some other AVRs have negative volume values ( e.g. -35 loud, -50 normal volume, -70 quietly....
.....
 for (i = 100; Volume < LMSVolumeMap[i] && i; i--);
			Volume = (i * Device->Config.MaxVolume) / 100;
			if (Device->Volume == Volume) break;
			Device->Volume = Volume;
                            .....
.......
If I set MaxVolume to -40 (nearly very load) then the calculation was

at i = 100   : 100 * (-40) / 100 = -40  
at i = 50     : 50   * (-40) / 100 = -20  (but "-20" > MaxVolume)   
at i = 10     : 10 * (-40) / 100 =  -4    (but "-4" > MaxVolume) 

So no other value then -40 will be send to the AVR...right ?

Can this be my problem ?

   Thank you

regards
   Thorsten

**Comment by philippe44** [comment]
Some have negative numbers in their Ui and feedback loop, but they are still commanded by UPNP Volume 0..100. My Marantz is the same way and works fine with 0..100 command, which is the UPnP standard way

**Comment by guny74** [comment]
Hello,

thank you for your reply. I used the positive  max volume  values in the
past, but it did noct work....

After upgrade and changing  from negatives to positive max volumes values
again, it work now.

Thank you

Regards

Am Mo., 6. Aug. 2018 um 23:35 Uhr schrieb philippe44 <
notifications@github.com>:

**Comment by philippe44** [comment]
Good
