### ISSUE TITLE
LMS-to-uPnP - GGMM E2 WLAN speaker battery information

### ISSUE THREAD

**Issue by chb16** [philippe44/LMS-to-uPnP#27]
Hi,
i have the wlan speaker above. When i'm using the app, the battery information are in there.
Is it possible to get these information to the lms?

I sniff the stream with packet caputre between app and phone. see the example below (no chance to put the caputre stream inside these window, it will cut most information)
here as a link:
https://pastebin.com/fMdFisgb

**Comment by philippe44** [comment]
Certes main je ne vois pas ou les lecteurs LMS on un emplacement dans la UI pour une indication de charge

**Comment by chb16** [comment]
No problem ;) I need it to get the information in my homeautomation system (fhem). It's correct, the LMS have no UI for that.

**Comment by philippe44** [comment]
How were you expecting to access that data from my plugin?

**Comment by chb16** [comment]
I use the fhem plugin from "ChrisD70-97_SB_SERVER.pm" [https://github.com/ChrisD70/FHEM-Modules](url).  He get the information over playerpref

**Comment by philippe44** [comment]
long wait but ... I've pushed in the dev repo version 1.7.0.1 which adds battery information for GGMM the following way. The "voltage" field of the squeezelite instance that represents the GGMM is split into 2 fields of 8 bits:
- upper 8 bits: 0 = unplugged, 1= plugged
- lower 8 bits = battery %

Unfortunately, the plugged/unplugged works on my GGMM-E5, but the % is always 0, I don't know why and this is not a bug in the way I get the value: I traced the UPnP raw response, and it *does* contains 0.

Hope the fhem dev will be able to do something with that

**Comment by philippe44** [comment]
Closed for inactivity
