### ISSUE TITLE
ERROR LOADING CONFIG FILE

### ISSUE THREAD

**Issue by powerpolly** [philippe44/LMS-to-uPnP#28]
hi,
I have the LMS Server configuried and can play music to a squeezelite client on my laptop, everthing works fine.
Now I'd like to have an "old" android mobile phone to act as squeezeclient. I installed/started a DLNA app on the phone and clicked "Generate configuration file" on the bridge. unfortunately I do not get the phone listed. I tried several DLNA apps but no one gets listed. What am I missing here?

background Info: I have integrated LMS in my home automation solution (openhab) and can send voice messages to squeezeclients. the old phone shall be put permanently in the kitchen and serve as homeautomation GUI and also as sound device.... 

hias@homeserver:/var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/UPnPBridge/Bin$ ./squeeze2upnp-x86-64 -i config.xml
[12:13:49.658854] main:1493 Starting squeeze2upnp version: v1.1.2 (Aug 19 2018 @ 23:06:44)
[12:13:49.658980] main:1501

!!!!!!!!!!!!!!!!!! ERROR LOADING CONFIG FILE !!!!!!!!!!!!!!!!!!!!!

[12:13:49.711264] Start:1272 Binding to 192.168.1.106:49153
[12:14:10.912250] Stop:1295 stopping squeezelite devices ...
[12:14:10.912418] Stop:1299 terminate update thread ...
[12:14:10.912634] Stop:1304 terminate main thread ...
[12:14:10.912832] Stop:1308 stopping UPnP devices ...
hias@homeserver:/var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/UPnPBridge/Bin$

**Comment by philippe44** [comment]
if no app is listing your android client, then it's not a UPnP renderer

**Comment by powerpolly** [comment]
can you tell me which App is a valid UPnP renderer?

**Comment by philippe44** [comment]
BubbleUPnP might be. But you't better use SqueezeCtrl that can include an option client which then emulates a real squeezelite

**Comment by philippe44** [comment]
Closed for inactivity
