### ISSUE TITLE
CLI port hard coded

### ISSUE THREAD

**Issue by dwhile** [philippe44/LMS-to-uPnP#29]
The port used for the CLI interface is currently hard coded into this plugin. LMS allows you to change the CLI port so this plugin should either take that value or allow it to be changed.

This is a particular problem on the later Fedora releases as they ship with a maintenance interface program (cockpit) running on port 9090. So either you have to remove cockpit or change LMS to run on a different port. I changed to port 9091 but then this plugin doesn't get the metadata due to looking on port 9090.

**Comment by philippe44** [comment]
Yes I know but sor far I'm not aware of a way for an application to query from LMS it's CLI port. I've suggest a LMS change that would allow it to be discovered alongside the server

**Comment by dwhile** [comment]
I understand. Could you implement it as a command line option for the time being? I note that you can specify command line parameters in the plugin settings.

**Comment by philippe44** [comment]
Should be corrected now
