### ISSUE TITLE
Running Squeezebox-Player needed?

### ISSUE THREAD

**Issue by MaDe74** [philippe44/LMS-to-uPnP#31]
Hi there,
a couple of days ago I ran into this plugin and am totally happy as it makes my Audiodata Audiovolver II Renderer work like it was a Squeezebox (you can add this device to the list of compatible devices).

So far so good. Until today. I decided to skip my Logitech Transporter out of my stereo lineup and just use the Audiovolver as renderer instead.

But here comes the issue:
Now "Squeeze Ctrl", the App I use to control playback doesn't find a renderer ("not connected to a player" / "can't find player") anymore. Before I could choose between Transpoter and Audiovolver. This is pretty disappointing as I just yesterday sold my Transporter and thus have no playback anymore.

Any chance to fix that? So LMS will work if JUST a uPnP-Device (and no Squeezebox) is connected to LMS?

Many thanks in advance, kind regards from germany,
Marcel

![screenshot](https://user-images.githubusercontent.com/44725591/47952095-9e4a5880-df6a-11e8-9e61-b4822c61075c.JPG)

**Comment by MaDe74** [comment]
A BIG SORRY... issue solved. There seemed to be network-connection problems with the Audiovolver. Running fine again, making me a happy man ;-)

**Comment by MaDe74** [comment]
Okay, after a couple of weeks I'm sorry to have to reopen this issue. Same situation as above, I'm in trouble with my preferred media-renderer (Audiovolver II by Audiodata).

Most times it is recognized when starting LMS and after that the renderer. Sometimes it is not recognized. 
Ordinary issue: After a certain time (e.g. 20 Minutes) playback stops. The renderer still is shown up in my Squeeze Ctrl. App as well as in the Squeeze-Control iny my PC-Browser but no way of having playback again. After some more minutes the renderer is gone within the Squeeze-Control. Even restarting LMS and the renderer most times does not solve the situation.

I by now completely read through the user guide (though not understanding everything due to lacking english as well as lacking technological knowledge), tried many changes within the settings, but I stay stuck with that problem.

Frankly said I have no idea where is prob is located. The renderer is recognized by e.g. BubbleUPnP as recommended controll-App by the manufacturer of Audiovolver and runs fine with BubbleUPnP. It is also detected by Fing in the LAN. 

But neither LMS nor "AV Media Controller" by Developer Tools for UPnP™ Technology do recognize the Audiovolver as renderer after is has "gone".
Attached you'll find some info concerning the Audiovolver II when it is detected.

I really really would appreciate a solution on this...

![audiovolver_01](https://user-images.githubusercontent.com/44725591/50087324-f0d09300-01ff-11e9-8e02-12a02746a637.JPG)

![audiovolver_02](https://user-images.githubusercontent.com/44725591/50087340-fb8b2800-01ff-11e9-9e1a-bb55b7833ed9.JPG)

![audiovolver_03](https://user-images.githubusercontent.com/44725591/50087345-00e87280-0200-11e9-82e3-1d3142bf4797.JPG)

![audiovolver_04](https://user-images.githubusercontent.com/44725591/50087348-06de5380-0200-11e9-88df-ba370c21f608.JPG)

**Comment by philippe44** [comment]
What is your *exact* network topology (all access modes, routers, CPL ...)

**Comment by MaDe74** [comment]
Hi philippe, thanks for your response.

As with my earlier request it happend that after this request (that went along with updating the plugin to the latest version 1.75) no issues occurred anymore.

But anyway, my network in means of those units that are used for audio streaming is as follows:
QNAP TS-119, directly connected to
AVM Fritzbox 7490 connected to
D-Link DGS-1008D connected to
D-Link DGS-1005D connected to renderer.

What do you mean with "all access modes" as well as what is "CPL"?

Kind regards,
Marcel

**Comment by philippe44** [comment]
Hi - I was thinking all the way to access your network, i.e. WiFi, ethernet and CPL ... = Power Line Carrier  (sorry, I used the French acronym)

**Comment by MaDe74** [comment]
Hi philippe44,

thanks for getting that clear. 

In fact my network contains all three kind of ways to access network:
LAN-Cable (which is the way my NAS on which SBS is installed and the renderer communicate) as well as a WiFi-accesspoint (mainly for bringing by Smartphone online but also for steering SBS via Smartphone in the LAN) as well as a Devolo PowerLine for bringing internet into other parts of the house.

Kind regards,
Marcel

**Comment by philippe44** [comment]
I forgot to follow-up. Likely, some of these network segment is blocking multicast.

**Comment by MaDe74** [comment]
No prob ;-)

Just checked the hardware again. The two D-Link DGS-1008D switches that so far appeared to be a good, reliable choisc do not support multicast as I had to find out. Seems as if I will have to go for something new...

Just to make it all more strange there is a new "behaviour" to report. In this very network there is two renderers I can use Squeezebox with:

1. Audiodata's Audiovolver II (preferred renderer)
2. Oppo UHD 203.

The problem described as that the Audiovolver is "gone" in the list of renderers on my SqueezeControl App somehow seems to be connected with that second renderer:
If I start with the Audiovolver only (Oppo in standby) problems as described above ony occurr rarely by now. That's why I didn't react on the spot on yur latest reply, I wanted to check out actual "behaviour".

But once I switch the Oppo to "on" and after that to "off" again (just this - it's indepedend if I use the Oppo as Squeezebox-renderer or not in that constellation) Playback on my Audiovolver stopps a couple of minutes after I switched the Oppo to "off". Switching the Oppo to "on" again and leaving it that then allows audio-playback with the Audiovolver again.

So it seems as if the "appearance" of the Oppo in the Network somehow determines the function of the Audiovolver in combination with the Squeezebox-Server. 

Pretty weird, but I have testest this by now a couple of times - it's reliable. Switchin the Oppo to "on" brings the Audiovolver back into playback.

**Comment by MaDe74** [comment]
Hi there,

after a while I think it's time to come back on this issue. Following your hint I bought two new Network-switches that were supposed to support multicast. That didn't bring a solution, even worse as this way my renderer "Audiovolver" wasn't recognized by my Squeezebox at all. Pretty disspointing to have spent 88 Euro for nothing.

In the end I achived functionality by skipping both of the Network-switches out of the line and straight-wire the renderer to my modem, to wich the NAS is directly connected, too. Since then ev'rything works fine, the Audiovolver is detected as soon as I switch it on and there so far is no stops in playback or any other hassle to report.

Many thanks to you, philippe44! Maybe this would be a worth hint in FAQ to the plugin - if there is connecttion problems try a "as far as possible straight-wire" in order to sort out problems caused by external/additional devices within the LAN.

Kind regards,
Marcel
