### ISSUE TITLE
xiaomi network speaker

### ISSUE THREAD

**Issue by fthc59** [philippe44/LMS-to-uPnP#32]
Bonjour, voilà j'utilisais trois enceintes xiaomi network speaker avec votre plugin, jamais aucun soucis, merci pour votre travail. mais depuis que j'ai mis à jour deux d'entre elles (oui je n'aurais pas dû) celles-ci même si elles sont visibles par le bridge, incapable d'envoyer une musique dessus, j'ai modifié le http type en "no lenght" et retiré le send ICY metadata comme préconisé mais rien à faire. Pourtant en utilisant une application android sur mon smartphone pour tester (mediaHouse Upnp/DLNA) celles-ci fonctionne avec . Du coup je n'ai plus qu'une enceinte de fontionnelle sur les trois, j'ai testé tous les modèles du plugin mais aucune config ne semble marcher. avaez vous une idée ? merci par avance

**Comment by philippe44** [comment]
Il me faudrait le log en mode debug (additional debbuging to 'all'). Stoppe le bridge, efface d'abord le fichier (clear) et relance le bridge

**Comment by fthc59** [comment]
Merci pour votre aide, voilà le fichier de log
[upnpbridge-log.log](https://github.com/philippe44/LMS-to-uPnP/files/3076807/upnpbridge-log.log)

**Comment by philippe44** [comment]
Je ne vois pas, l'enceinte prétend bien commencer à lire mais l'indicateur de temps écoulé ne progresse pas. Peut-être ajouter dans la ligen "extra command line"  l'option suivante "-d all=sdebug". Le fichier produit sera très volumineux mais ça me donnera une meilleure idée.

**Comment by fthc59** [comment]
Voilà le fichier : 
[upnpbridge-log (2).log](https://github.com/philippe44/LMS-to-uPnP/files/3076903/upnpbridge-log.2.log)

L'enceinte ne produit aucun son et sur LMS la lecture ne se lance pas
Merci

**Comment by philippe44** [comment]
Je ne vois pas de tentative de lecture

**Comment by fthc59** [comment]
Merci philippe44 pour ton aide, sinon tant pis je sais maintenant que les speakers xiaomi, flashé avec le firmware AI, ne sont pas compatible avec ton bridge. je vais devoir les brancher avec mes Audiocast d'aliexpress en jack (c'est nul je sais), eux au moins fonctionnent très bien avec ton plugin. Si tu habites en France, je peux t'envoyer une des enceintes, je suis sure que le DLNA fonctionne (fonctionnel sous android et sur pc )... Au juste merci aussi pour le plugin chromecast. LMS + tes deux bridges c'est de la "balle". 
[upnpbridge-log avec tentative de lecture mp3 et radio.log](https://github.com/philippe44/LMS-to-uPnP/files/3077244/upnpbridge-log.avec.tentative.de.lecture.mp3.et.radio.log)

**Comment by philippe44** [comment]
Ce qui est étrange c'est que ce log dit que tout se passe bien. Tu es sûr que ce n'est pas simplement le volume qui est à 0?

**Comment by fthc59** [comment]
Oui, oui sûr. lorsque j'appui sur play, instantanément ils revient en "stop" il n'y a pas de lecture. je vais essayer de voir dès que possible en sniffant les trames réseaux entre xiaomi et LMS + Mediahouse (ou bubble). merci en tout cas

**Comment by fthc59** [comment]
Salut,
est ce cela te parle ? je te mets la différence que j'ai pu voir sur les commandes entre la fonctionnelle sous LMS 192.168.31.26 (ancienne version) et la non fonctionnelle sous LMS 192.168.31.97 (nouveau firmware). Toutes les deux fonctionnent en directe sans passer par LMS et le bridge

Protocole AV-Transport :
Service Description 
- http://192.168.31.26:9999/479980a4-1037-f01f-0744-d66a6e855349-MR/Upnp/upnp.org-AVTransport-1/service.xml
- http://192.168.31.97:9999/AVTransport1.xml

Device Description
- http://192.168.31.26:9999/479980a4-1037-f01f-0744-d66a6e855349/Upnp/device.xml
- http://192.168.31.97:9999/e581e1a1-a1d2-43db-b57c-c947538dc381.xml
Connection manager 
- http://192.168.31.26:9999/479980a4-1037-f01f-0744-d66a6e855349-MR/Upnp/upnp.org-ConnectionManager-1/service.xml
- http://192.168.31.97:9999/ConnectionManager1.xml
Qplay :
- http://192.168.31.26:9999/479980a4-1037-f01f-0744-d66a6e855349-MR/Upnp/tencent.com-QPlay-1/service.xml
- http://192.168.31.97:9999/QPlay1.xml

et pour les infos général :
192.168.31.26
manufacturerMi, Inc.
modelDescriptionThe Mi WiFi SoundBox
modelNameS602
modelNumberS602
qq:X_QPlay_SoftwareCapability{"_":"QPlay:2","$":{"xmlns:qq":"http://www.tencent.com"}}
dlna:X_DLNADOC{"_":"DMR-1.50","$":{"xmlns:dlna":"urn:schemas-dlna-org:device-1-0"}}
dlna:X_DLNACAP{"_":",","$":{"xmlns:dlna":"urn:schemas-dlna-org:device-1-0"}}

et pour 192.168.31.97
manufacturerMi, Inc.
modelDescriptionThe Mi AI SoundBox
modelNameS12
modelNumberS12
qq:X_QPlay_SoftwareCapability{"_":"QPlay:2\n ","$":{"xmlns:qq":"http://www.tencent.com"}}
dlna:X_DLNADOC{"_":"DMR-1.50\n ","$":{"xmlns:dlna":"urn:schemas-dlna-org:device-1-0"}}
dlna:X_DLNACAP{"_":",\n ","$":{"xmlns:dlna":"urn:schemas-dlna-org:device-1-0"}}

**Comment by philippe44** [comment]
Je ne sais pas - Si j'ai l'occasion de mettre la main sur ce type de HP un de ces jours, je regarderai

**Comment by philippe44** [comment]
Closed for inactivity

**Comment by CM-330** [comment]
Bonjour,
J'ai eu un souci équivalent avec la même enceinte, et a priori le problème est apparu avec une mise a jour automatique du plugin. Du coup j'ai désactivé les MAJ auto et j'ai remis le plugin en version 1.20 et depuis tout remarche sur l'enceinte. En espérant avoir aidé ou tout du moins donné une piste!

**Comment by philippe44** [comment]
Très bizarre parce que je n'ai pas fait de modification impactant

1.25.1
 - tabulate volume conversion
 
1.25.0
 - do not delete Sonos context when group is created to manage volume
 - volume is now a double to allow scaling in groups
 - do not use mute anymore when paused, let volume go to 0 and then restore it
  
1.20.2
 - use correct 'os' and 'osName' for freebsd
 
1.20.1
 - offer freebsd helper as well

**Comment by CM-330** [comment]
Oui je ne comprends pas non plus, j'avais plus bien lu le changelog des modifications et j'ai tenté cette réinstall en dernier recours car je ne comprenais pas d'ou cela pouvais provenir. Et je me suis surtout rappelé que j'avais les MAJ auto d'activée ce qui m'a fait réinstallé une ancienne version.
Après je n'ai pas retesté avec une version entre la 1.20 et la 1.25.

**Comment by Znikos** [comment]
Bonjour à tous,
Même problème que précédemment...
Comment est-ce que tu fais pour repasser en 1.20. Le fichier XML pointant vers la dernière version ?
Je suis un peu perdu...

**Comment by dckiller51** [comment]
Si besoin j'ai mis une solution pour downgrader en 1.4.
https://community.jeedom.com/t/downgrade-xiaomi-speaker-network-upnp-la-soluce/38606/2

**Comment by chatainsim** [comment]
@dckiller51 Désolé de déterrer le sujet mais comment tu démonte l'enceinte ? Je ne vois pas de vis. Une astuce ? Merci et merci pour le guide que j'utiliserai une fois l'enceinte ouverte 😀

**Comment by dckiller51** [comment]
> @dckiller51 Désolé de déterrer le sujet mais comment tu démonte l'enceinte ? Je ne vois pas de vis. Une astuce ? Merci et merci pour le guide que j'utiliserai une fois l'enceinte ouverte 😀

Slt, de mémoire il a une vis sous l étiquette. Ensuite c est des clips tout autour. Si tu n y arrives je regarderai demain.

**Comment by chatainsim** [comment]
> > @dckiller51 Désolé de déterrer le sujet mais comment tu démonte l'enceinte ? Je ne vois pas de vis. Une astuce ? Merci et merci pour le guide que j'utiliserai une fois l'enceinte ouverte 😀
> 
> Slt, de mémoire il a une vis sous l étiquette. Ensuite c est des clips tout autour. Si tu n y arrives je regarderai demain.

Effectivement c'était bien ça. Deux vis sous l'étiquette et quelques clips. Merci beaucoup
