### ISSUE TITLE
Plugin won't /can't create config file in Ubuntu 18.04

### ISSUE THREAD

**Issue by Blackhawke** [philippe44/LMS-to-uPnP#33]
For some reason, the plugin is unable to create/save its config file on Ubuntu 18.04. I've tried in two different browsers. I've checked the permissions in the folder tree. I even tried creating a blank config file for the plugin to overwrite. (That just screwed everything up. So I know it's reading the file.) Nothing makes a difference.

Any ideas?

**Comment by philippe44** [comment]
It's unlikely or a Ubuntu version or a file access problem but rather the config file that is not being created because no player can be found. Discovery fails for different reasons, including firewall, NAT, being in a VM or behind a router that does multicast filtering

**Comment by Blackhawke** [comment]
> It's unlikely or a Ubuntu version or a file access problem but rather the config file that is not being created because no player can be found. Discovery fails for different reasons, including firewall, NAT, being in a VM or behind a router that does multicast filtering

Yes, I'm aware of that/those issues. Our servers provide remote access to a variety of things, including our own, private git server. Unfortunately, for some reason, your plugin will not let me assign a specific port that I can then require the player to use. The best I've been able to do is keep the "use lms network interface" box checked, which isn't working. So, as it stands, the player (RoxBox) is expecting access to the server (your plugin) and your plugin appears to expect access to the player, so neither is seeing the other.

**Comment by philippe44** [comment]
I'm not sure I'm following. There are 2 distinct things: the discovery process which uses SSDP and for which standard ports must available, then when starting to playback, there is a HTTP server that I create where the  player can GET the audio data. The latter does not work with NAT and requires ports to be opened, but here you can set the base port and I'm trying up to 32 ports from the base port. The former is a general multicast issue.

**Comment by Blackhawke** [comment]
I'm not sure I'm following either, to be honest. I installed Kodi, and two different players discovered it easily, but not yours. In any event, we decided to just dump LMS for Plex.

So thank you for your help.
