### ISSUE TITLE
probleme démarrage LMS-to-uPnp

### ISSUE THREAD

**Issue by nicobros** [philippe44/LMS-to-uPnP#34]
Bonjour, 

  Je me permet de te soumettre mon soucis car je suis en train de tourner en rond et je ne trouve pas de solution.
  J'ai LMS qui est installé sur un NAS asustor, et j'ai rajouté ton plug in pour appairer une enceinte qui est sur le réseau, alors pendant un moment tout fonctionnait et du jour au lendemain plus rien ne fonctionnait. J'ai supprimé LMS de mon nas et j'ai refait toute l'installation.
  Cependant le serveur uPnP refuse de rester démarré, il passe bien en running mais repasse en not running et je ne comprend pas pourquoi.
  Peux tu m'aider à résoudre mon probleme ?

**Comment by philippe44** [comment]
Il me faudrait le log

**Comment by nicobros** [comment]
merci pour ta réponse, comment puis je te fournir le log ?

**Comment by philippe44** [comment]
Dans la webUI de LMS, section des paramètres de mon plugin

**Comment by nicobros** [comment]
Bonjour, je te joins le log (si ça ne correspond pas, dis le moi), pour avancer un peu dans le soucis : j'ai réinstaller LMS sur un raspberry au lieu du nas qui me sert d'habitude (avec une autre adresse IP fixe) car je me suis demandé si cela ne venait pas de mon nas. 

Verdict : cela me fait exactement la meme chose, je pense que je ne dois pas faire quelque chose de bien mais je ne vois pas quoi, surtout que cela fonctionnait avant.

[log lms.txt](https://github.com/philippe44/LMS-to-uPnP/files/3563641/log.lms.txt)
Merci d'avance pour ton aide

**Comment by philippe44** [comment]
Le problème des NAS c'est que c'est "presque" un Linux standard, masi aps totu à fait. Quelque chose fait planter squeeze2upnp systématiquement. Essaie la version -static

**Comment by nicobros** [comment]
j'ai tenté aussi en static et ça fait la même chose, je suis passé sur un raspberry car sur mon nas je n'avais pas accès à la dernière version de lms, je me suis dit que cela pouvait venir de là mais non.
pour le plantage ça pourrait être un matériel connecté en upnp ou uniquement un soucis logiciel ?

**Comment by philippe44** [comment]
Ca ressemble à quelque chose qu'un des lecteur envoie à squeeze2upnp et qui le fait se planter. Peux-tu essayer avec les lecteurs 1 par 1?

**Comment by philippe44** [comment]
Closed for inactivity
