### ISSUE TITLE
Crash Upnp

### ISSUE THREAD

**Issue by ludisnet** [philippe44/LMS-to-uPnP#35]
Bonjour,

Debian 10.3 ; LMS 7.9.3 (fresh install)

le serveur Upnp crash et redémarre sans cesse, log ci-joint, avez-vous une explication ?

[upnpbridge-log.log.txt](https://github.com/philippe44/LMS-to-uPnP/files/4237854/upnpbridge-log.log.txt)

**Comment by philippe44** [comment]
Probablement résolu dans la dernière version. Certains lecteurs remontent des paramètres UPnP incorrects.

**Comment by ludisnet** [comment]
Merci, problème résolu avec la dernière version !

Merci.

Ludis
