### ISSUE TITLE
Zone Discovery - Denon

### ISSUE THREAD

**Issue by anlx-sw** [philippe44/LMS-to-uPnP#39]
Hi,
I just integrated your plugin and it works great for me onkyo receiver. 

on my denon avr-x1400h it seems that the playback is always starting in zone 2 (where i have no speakers connected). in lms under players there are no zones displayed and i couldn't find any place where to select a zone.

I suspect that the discovery is somehow failing. if i use the microsoft upnp explorer the device looks like this:
![grafik](https://user-images.githubusercontent.com/16399949/79123568-c1517c80-7d9a-11ea-9059-d08a53ef13b8.png)

is this a problem with the plugin or an error on my side somehow?
any idea on how to fix this?

Thanks!

**Comment by philippe44** [comment]
I don't handle Zones except for Sonos

**Comment by anlx-sw** [comment]
thanks for the answer. 
it seems it wasn't a zone problem anyways. i found in some other thread where you answered some settings for heos - and with this settings and now  i could get the playback to work.

next thing now is on how to get rid of a 5 second time difference between two players.

**Comment by philippe44** [comment]
> next thing now is on how to get rid of a 5 second time difference between two players.

You can't - UPnP does not support synchronization

**Comment by anlx-sw** [comment]
ok - thanks for the fast answer. 

also thanks for the detailed documentation you created for this project. helped me get this thing going.
