### ISSUE TITLE
Metadata character sets

### ISSUE THREAD

**Issue by Pastim** [philippe44/LMS-to-uPnP#4]
Just to make a note of a very low-priority issue (in amongst the flurry of posts on the LMS forum), the character sets on metadata need some attention.  Characters like ' appear incorrectly on my M1 CLiC renderer showing as &apos;  

There are probably other issues as well.  I use most of the normal punctuation, most European variations, and some Asian (I tested Japanese and it works).

**Comment by Pastim** [comment]
Is there anything that can be done about this or not?  It's OK with UPnP servers and the same metadata,

**Comment by philippe44** [comment]
solved now

**Comment by Pastim** [comment]
All good - thanks.
