### ISSUE TITLE
UPnP player not shown in drop down menue

### ISSUE THREAD

**Issue by picofried** [philippe44/LMS-to-uPnP#41]
Hello, I installed the UPnP bridge in my LMS on the Synology NAS (see the image for LMS info) and see my Libratone ZIPP 2 in the UPnP settings page.
But I cannot see this additional player in the drop down menu of the LMS GUI. I have attached pictures to visualize my issues.
I would highly appreciate your help on this since I could not find any forum where such an issue was discussed before.
Thank you so much and best regards

![UPnP seetings](https://user-images.githubusercontent.com/64325007/97802780-23de6d00-1c46-11eb-8a6d-2ef001ffc5de.PNG)
![Player missing](https://user-images.githubusercontent.com/64325007/97802788-30fb5c00-1c46-11eb-9e81-5eee2ce837d6.PNG)
![LMS info](https://user-images.githubusercontent.com/64325007/97802792-35c01000-1c46-11eb-8800-10f427f9b0b9.PNG)

**Comment by philippe44** [comment]
You have not checked "Start the Bridge" option

**Comment by philippe44** [comment]
Closed for inactivity
