### ISSUE TITLE
upnpbridge crach

### ISSUE THREAD

**Issue by ludisnet** [philippe44/LMS-to-uPnP#42]
Bonjour,

le serveur Upnp crash et redémarre sans cesse, log ci-joint, avez-vous une explication ?

Logitech Media Server Version : 7.9.3 , sur un debian 9.3

ceci a eu lieu subitement suite à un redémarrage de la machine.

Merci.
Ludis

[upnpbridge-log.log.txt](https://github.com/philippe44/LMS-to-uPnP/files/5471215/upnpbridge-log.log.txt)

**Comment by philippe44** [comment]
Est-ce résolu par une version récente ?

**Comment by ludisnet** [comment]
Bonjour,

Après mise a jour, le plugin est fonctionnel.

Merci.

Ludis
