### ISSUE TITLE
playing on heos

### ISSUE THREAD

**Issue by bscuderi13** [philippe44/LMS-to-uPnP#44]
I tried installing your plugin on logitech media server and it finds my denon heos receiver just fine however I can't seem to play music to it. Not sure if its an actual bug or just me but any help would be appreciated.

**Comment by daniel1v** [comment]
I have the same problem, using LMS 8.1.0 on raspbian buster. Any ideas?

**Comment by daniel1v** [comment]
Here some additional info: I could not find plugin-specific errors in the log file. But when I select a player which was generated by LMS-to-UPnP and start playing, I get the following output:

`[21-01-09 14:31:50.4024] Slim::Player::Song::open (415) Error: Couldn't create command line for aac playback for [http://s6-webradio.antenne.de/antenne/stream/aacp?aw_0_1st.playerid=tunein.com]
[21-01-09 14:31:50.4097] Slim::Player::Song::open (415) Error: Couldn't create command line for mp3 playback for [http://stream.antenne.de/antenne/stream/mp3?aw_0_1st.playerid=tunein.com]
[21-01-09 14:32:41.4072] Slim::Player::Song::open (415) Error: Couldn't create command line for spt playback for [spotify://track:6V68CLsCg05KRTX1MgTC2V]`

This happens not just when I try to stream to my Denon AVR, but also to my Windows PC.

**Comment by daniel1v** [comment]
Another thing I could noticed, while playing around: When listening music from another source on my UPnP device and press a button in LMS (for example play / forward / rewind) my AVR stops playback. So it seems like there is some sort of connection. 

The issue also exists in LMS on Windows 10.

**Comment by marc-aurel** [comment]
HEOS devices need the following setting in upnpbridge.xml:

**<forced_mimetypes>audio/flac,audio/mp3,audio/aac</forced_mimetypes>**

**Comment by daniel1v** [comment]
> HEOS devices need the following setting in upnpbridge.xml:
> 
> **<forced_mimetypes>audio/flac,audio/mp3,audio/aac</forced_mimetypes>**

Thank you very much, this worked for me.

@philippe44 : maybe this could be added to the documentation or? I haven't found it there and I think HEOS devices are not uncommon.

**Comment by philippe44** [comment]
I'll add an entry in the prebuild-profiles

**Comment by bscuderi13** [comment]
This still isn't working for me... What am I missing?
<device>
<send_coverart>1</send_coverart>
<send_metadata>1</send_metadata>
<mac>aa:aa:aa:aa:aa:aa</mac>
<friendly_name>Denon AVR-X3500H</friendly_name>
<forced_mimetypes>audio/flac,audio/mp3,audio/aac</forced_mimetypes>
<enabled>1</enabled>
<accept_nexturi>1</accept_nexturi>
<mode>thru</mode>
<send_icy>1</send_icy>
<raw_audio_format>raw,wav</raw_audio_format>
<flac_header>1</flac_header>
<codecs>dsf,dff,aif,pcm,flc,mp3,ogg,aac,alc</codecs>
<udn>uuid:secret-maybe-not-sure-numbers</udn>
<seek_after_pause>0</seek_after_pause>
<name>Denon AVR-X3500H</name>
<L24_format>2</L24_format>
<sample_rate>192000</sample_rate>
<stream_length>-3</stream_length>
<max_volume>100</max_volume>
</device>

**Comment by bscuderi13** [comment]
is there something common that could be blocking it on my network? I tries streaming to an amazon fire tv as well to no avail

**Comment by martinhd** [comment]
I was working with the lmscommunity/lyrionmusicserver:latest docker image. <forced_mimetypes>audio/flac,audio/mp3,audio/aac</forced_mimetypes> made the connection to my Denon Dra-800 work. 
It was discovered as Denon not as Heos
Wouldn't it be nice to add this entry to the Denon section in profiles.xml too?
