### ISSUE TITLE
Update 1.49.1 -no config file generated

### ISSUE THREAD

**Issue by mcewant2** [philippe44/LMS-to-uPnP#45]
Hi Philippe - my Sonos Play1 was working fine with LMS until the updates to 1.49 and 1.49.1. Now when I try to use the uPNP /DNLA bridge, no config file is generated?

[LMS.pdf](https://github.com/philippe44/LMS-to-uPnP/files/5898309/LMS.pdf)

Thanks in advance for your help

**Comment by philippe44** [comment]
The differences between the two are really not related at all to device detection. It's just about SSL streaming

**Comment by starlir** [comment]
Philippe,

First install today on Mac OSX 11.3 Intel along with Roon Core.  My two Naim streamers were identified and the config file updated.  I was able to stream music to both and all working well.  I then attempted to create a Launch Daemon which failed on rebooting my Mac.  I decided to remove the device configurations from the config file and rerun setup with the -i switch.  It seems now that the config file will not update even though the log shows the streamers are found.  If I try to run LMS with the -x switch the streamers subscribe successfully but when trying to play music with the Roon client I get 'unable to connect to server with cli' and 'cannot get metadata' and the Roon client just sits waiting to start.  Thought I should post here as it seems to be a config file related issue.

**Comment by starlir** [comment]
Philippe,

Solved, essentially user error (me!) loading from the wrong directory.  Apologies

**Comment by Ulrar** [comment]
Hey,

Sorry, how did you fix this then ?
I'm also having an issue with this plugin not generating a config file, and not logging any errors.

Thanks

**Comment by starlir** [comment]
I just made sure I was explicit with the directory path to the executable and also to the config file, otherwise the configuration file will be created in the wrong directory, it will not be where you think it should be.

**Comment by Ulrar** [comment]
Ah, guess that's not the same issue I'm having then, using absolute paths doesn't resolve it.
Whatever I do the plugin isn't generating the config file for some reason

**Comment by Ulrar** [comment]
So since I can't get it to generate a config file, would you mind copy pasting yours here ?
I could try editing it out manually, maybe I can get it to work that way.

**Comment by philippe44** [comment]
There is no point in manually building a config file. If none is created it means that no player is detected and you have some kind of firewall/network issue

**Comment by Ulrar** [comment]
Would it not say so ?
I definitely have a player, which is getting detected fine by other devices
on the network.

Maybe the same issue as with AirPlay, the mdns is getting there fine but
the plugin isn't picking it up for some reason.
Chromecast is working well on the same instance though

**Comment by philippe44** [comment]
these a different ports and communication protocol. I assume you're in a docker container of some sort, right? Did you set it in host mode?

**Comment by Ulrar** [comment]
Docker yes, in macvlan mode so the container has it's own IP

**Comment by philippe44** [comment]
> Docker yes, in macvlan mode so the container has it's own IP
>
Well unfortunately, per first section of documentation, you must be in host mode, no NAT

**Comment by Ulrar** [comment]
Macvlan isn't NAT, it's giving the container it's own interface, which is
bridged on the host.
So in effect it's like running on host mode, but with it's own IP

**Comment by philippe44** [comment]
I'm not using docker much, so I'm not familiar with its different configuration, all I can say is that if nothing is discovered, it's likely due to some network issue where packets are dropped, especially multicast datagram. This is where you should look, there is unfortunately nothing there to change in the UPnP bridge

**Comment by Ulrar** [comment]
![image](https://user-images.githubusercontent.com/873423/109428225-08198680-79ee-11eb-852a-a6da4f4df538.png)

With your other plugins even if it's not finding a player, it still generates a config. Is this one different, is the above expected when it can't find a player ?

I'm not really familiar with UPNP/DLNA, is it mdns based too or does it work another way ?
I've got an mdns repeater and an igmp proxy on my router to bridge these across my networks, which is working well for chromecast.
As discussed in the other issue with your mdnssd tool I can see the Airplay address from the LMS docker container itself :
```
[10.0.0.254] 10.43.0.11 04515   00226C2D2A99@Bedroom._raop._tcp.local 0s ACTIVE
```
So the bridging is working, but the Airplay plugin isn't picking it up. 10.43.0.11 is my Airplay / DLNA device (an audiocast M5), and 10.0.0.254 is where the mdns repeater is running.

As for DLNA I can't see anything at all, but I'm not sure it's even supposed to show up in mdns. It looks like Spotify on my phone can actually see it, but it can't connect to it, is there some kind of check in the plugin that would prevent it from adding a device that it fails to connect to to the list maybe ?
I don't doubt I have an issue somewhere on my side, just running out of ideas of where to look.
Thanks

**Comment by philippe44** [comment]
mDNS is not used by UPnP at all, instead it uses SSDP. The file is not created when not player is found, I've changed that a while ago so that's expected. IGMP is usually a potential problem, have you tried going direct w/o that?

**Comment by Ulrar** [comment]
Hi, that's it.
My router (UDM Pro) has a bug currently, SSDP forwarding across subnet isn't working, they're supposedly working on a patch. I did put the audiocast in the same subnet as LMS for now and it works fine.
When they fix that bug it should hopefully also work across subnet just like chromecast.

Thanks for the help !
