### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by DrCWO** [philippe44/LMS-to-uPnP#48]
Hello Phillipe,
I try to build your application on a Raspberry Pi with an up to date Raspbian. This is what I did:
- git clone https://github.com/philippe44/LMS-to-uPnP
- cd LMS-to-uPnP/application 
- edit Makefile.armv6hf and make “CC = gcc”
- make -f Makefile.armv6hf

gcc -Wall -fPIC -ggdb -O2  -I. -I.. -I../valgrind/memcheck -I../valgrind/include -I../openssl/inc -I./squeezetiny -I./tools -I./squeeze2upnp -I./squeeze2upnp/inc -I../alac -I../flac/include -I../faad2/include -I../libmad -I../libvorbis/include -I../libogg/include -I../libopus/include -I../libopusfile/include -I../soxr/src -I../libupnp/1.6.19/ixml/inc -I../libupnp/1.6.19/upnp/inc -I../libupnp/1.6.19/build/inc -I../libupnp/1.6.19/threadutil/inc  -D_FILE_OFFSET_BITS=64 -DRESAMPLE -DCODECS -DUSE_SSL -D_GNU_SOURCE -Wno-multichar -Wno-unused-result -fdata-sections -ffunction-sections   -I. -I.. -I../valgrind/memcheck -I../valgrind/include -I../openssl/inc -I./squeezetiny -I./tools -I./squeeze2upnp -I./squeeze2upnp/inc -I../alac -I../flac/include -I../faad2/include -I../libmad -I../libvorbis/include -I../libogg/include -I../libopus/include -I../libopusfile/include -I../soxr/src -I../libupnp/1.6.19/ixml/inc -I../libupnp/1.6.19/upnp/inc -I../libupnp/1.6.19/build/inc -I../libupnp/1.6.19/threadutil/inc  ./squeezetiny/slimproto.c -c -o bin/armv6hf/slimproto.o
In file included from ./squeezetiny/squeezedefs.h:27,
                 from ./squeezetiny/squeezelite.h:25,
                 from ./squeezetiny/slimproto.c:40:
./tools/platform.h:65:10: fatal error: memcheck.h: No such file or directory
 #include <memcheck.h>
          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:77: bin/armv6hf/slimproto.o] Error 1

Would you pease tell me athat packages I have to install with "apt-get install" to be able running the makefile?
Are there also other things that have to be done to be able to build it?

I like to make some changes in your code and therefore need to be able to build the application

**Comment by philippe44** [comment]
This one is valgrind missing

**Comment by DrCWO** [comment]
Hi Phillipe, 
finally I was able to build it on my Raspbian Pi. There was a lot to install and also some include files and libs to copy so they got at the right place. 
I also ran in trouble with SSL but I disabled it in the Makefile because I have no use of it.
Just for your information: I have set up a list with all the commands I needed to make it compile on the Pi with the default Raspbian. I will be happy to mail it to you, so you can publish it for others. Please drop me a line at to info (AT) definiteAudio (dot) de and I will send it.
