### ISSUE TITLE
LMS Usage Issues？

### ISSUE THREAD

**Issue by hehehezjb** [philippe44/LMS-to-uPnP#49]
Hi, hello. I recently used the Huawei Sound X speaker with the LMS-to-UPnP. I have a few questions.
(1) When a song is played repeatedly for 9 to 10 times, the LMS does not send the URL of the next song to the speaker. As a result, the playback stops.
(2) The playback stops unexpectedly. Check the speaker log. The speaker cannot connect to the server (why is the server disconnected suddenly?).
(3) The playback stops unexpectedly when the list is played cyclically.
Thank you for your answer.

**Comment by philippe44** [comment]
It's better to go on LMS forum and ask questions there
