### ISSUE TITLE
Compatibility with Mark Levinson 5101

### ISSUE THREAD

**Issue by tokenviking** [philippe44/LMS-to-uPnP#50]
Hi, I have got this working with roon and Mark Levinson 5101. However, it is limited to PCM 48000. The ML5101 will go to PCM 192000 and DSD 128.

Is there a way to edit the config so I can get the high rez options?

I attach the config.xml file.

[config.zip](https://github.com/philippe44/LMS-to-uPnP/files/6352169/config.zip)

Many Thanks,
Tony

**Comment by philippe44** [comment]
In the Settings, you can set max frequency (LMS/Settings/Advanced, UPnPBridge in the dropdown box)

**Comment by tokenviking** [comment]
Thanks Philippe, found it.

But now roon discovery will not work unless LMS server is stopped?

Is there a standalone version of this plugin where I can edit the config file. For example can I do that with the ifi-Bridge?

Many Thanks,
Tony

**Comment by philippe44** [comment]
Roon only works when LMS is disabled. Now, when you set the parameter form LMS, it writes the config file used by LMS and it stays permanently there. You can also use your favorite text editor to change the .xml file for the max sampling rate. The names of parameters are obvious. The plugin only need the .xml file to work, you can have as many as you want, just set the one to use 
on the command line.

**Comment by tokenviking** [comment]
Thanks Philippe,

That works up to PCM 192000. Very stable. I left it running overnight. What I missed was I only have to create and edit the config file once.

Sounds absolutely fantastic so you can definitely put Mark Levinson 5101 on the compatibility list. This network based DAC so much better than the USB DAC I was using before which was very well regarded in its day, but time flies.

Roon is still down-sampling dfs files but am I right that is because I have various DSP switched on like volume levelling and convolution so its down sampling to PCM?

Many Thanks,
Tony

**Comment by tokenviking** [comment]
Hi Philippe? 

The ML 5101 appears not to be reporting to the plugin that it supports DSD up to 5.6Mghz. Is there a way of forcing this in the config.xml file? For example with the Mime Types or other method? The current result is that in roon I do not get an option in device configuration for native DSD, just DSD over PCM and that does not work as I do not believe the ML 5101 supports DoP, only native DSD.

Many Thanks,
Tony

**Comment by philippe44** [comment]
That's because I'm an anti-dsd :smile: 

But joke aside, you have the \<forced_mimetype\> option to solev that

**Comment by tokenviking** [comment]
Ok thanks. But what forced mimetype do I need? I've tried for example:

<forced_mimetypes>audio/x-dsf,audio/x-dff</forced_mimetypes>

But that doesn't make any difference. I still do not get native DSD as a SqueezeLite configuration option in roon.

**Comment by philippe44** [comment]
I'm sorry but I really don't know. I think some others had success using this bridge and roon in dsd, I remember tweaking a few things for that, but as said and joke aside, dsd is really not of any interest to me so I've never spent a lot of time on that. You will probably have better luck on Roon's forums.

**Comment by philippe44** [comment]
Closed for inactivity
