### ISSUE TITLE
Link to sourforge broken

### ISSUE THREAD

**Issue by igufi** [philippe44/LMS-to-uPnP#54]
Hi, the link mentioned in the readme.md, "https://sourceforge.net/projects/lms-to-upnp" seems to be broken. Is the lms-to-upnp package available elsewhere?

**Comment by philippe44** [comment]
I've updated the readme, but the main access to the plugin is through LMS, no need to install manually

**Comment by igufi** [comment]
Understood, I just realized that I only needed the binary and dlls anyway. I have a hacky Rube Goldberg-esque setup to catch the LMS stream from Roon and send it over to foobar2000 so that I can apply Dirac room correction (VST plugin) to the stream and then finally send it over to my streamer for playback.
