### ISSUE TITLE
lms to upnp selects the wrong NIC

### ISSUE THREAD

**Issue by NicoVermeir** [philippe44/LMS-to-uPnP#6]
my LMS runs on a system with vmware installed, giving me a few virtual network cards. When I'm running the upnp discovery it automatically selects one of those virtual network cards, those cards are not connected to my real network so none of my players are found.

**Comment by philippe44** [comment]
I'll see how to add a parameter to force binding of the uPnP client to one of the NIC

**Comment by philippe44** [comment]
Parameter added in 0.2.0.0
