### ISSUE TITLE
Error when playing in Sonos player

### ISSUE THREAD

**Issue by TiagoOliveiraMarques** [philippe44/LMS-to-uPnP#7]
When streaming to a sonos player, in the LMS it appears that the sonos is playing but in the sonos control app it says the media has invalid format.

However, the music metadata appears correctly.

**Comment by philippe44** [comment]
what <stream_length> parameter did you choose. As indicated in the COMPATIBILITY file, Sonos requires, for example a value like 1000000000 here, cannot work with -1,-2,-3,-4. I have a play:3,:5 and :1 and can confirm it works

**Comment by TiagoOliveiraMarques** [comment]
Sorry, I missed those notes. I was trying with a Sonos Connect. Next time I have a chance I'll try with the changes you mentioned.

**Comment by philippe44** [comment]
no worries - let me know if it works for you !

**Comment by TiagoOliveiraMarques** [comment]
And that was the problem. Thanks.
