### ISSUE TITLE
Plugin not installing in LMS

### ISSUE THREAD

**Issue by grtessman** [philippe44/LMS-to-uPnP#8]
So I did RTFM, and per your user guide here: 
https://github.com/philippe44/LMS-to-uPnP/blob/master/0.2.2.0/New%20user%20guide%20(with%20plugin).pdf

I have added the URL mentioned in LMS plugins: 
http://dl.dropboxusercontent.com/u/26754471/squeezecenter/repo.xml

But it returns 404 Not found.

Then, I have tried the URL listed here: https://github.com/philippe44/LMS-to-uPnP
which is:
http://dl.dropboxusercontent.com/u/26754471/squeezecenter/repo-stable.xml

It seems to redirect to https URL instead of: https://dl.dropboxusercontent.com/u/26754471/squeezecenter/repo-stable.xml

Then logitech media server doesn't add the URL with https apparently, instead it says: Bad repository http://dl.dropboxusercontent.com/u/26754471/squeezecenter/repo-stable.xml - Redirection limit exceeded

Which, I assume would be the same results as using RAW from github (still https):
https://raw.githubusercontent.com/philippe44/LMS-to-uPnP/master/repo-stable.xml

Plugin doesn't seem to install - please advise.  I'm running LMS on Linux x86 (Netgear ReadyNAS) box.

Strangly and possibly unrelated, even though plugin doesn't show in the list as installed - my Nexus 5 phone started spontaneously playing music with no way to kill it except reboot... related?

**Comment by philippe44** [comment]
This is problem due to the fact that I'm using dropbox and, as you said it redirects to HTTPS and some devices do not have perl IO::Socket::SSL install. Some users on Netgear have success adding it through 'apt-get install libio-socket-ssl-perl'.  

Same thing would happen with raw github.

For the Nexus, I really don't know because nothing is downloaded nor installed, as LMS does not even find the repo, so there can not be an interfence

**Comment by grtessman** [comment]
Thanks for your reply.

You don't have it available on http anywhere else?  Looks like that package won't install on my NAS OS4 x86.  :-(  Bummer.

ReadyNAS3:~# apt-get install libio-socket-ssl-perl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libio-socket-ssl-perl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package libio-socket-ssl-perl has no installation candidate

**Comment by philippe44** [comment]
I just setup a sourceforge repo
http://sourceforge.net/projects/lms-to-upnp/files/repo-sf-stable.xml

**Comment by grtessman** [comment]
You rock man - that worked!  Thank you very much!  Plugin now installed.  I'll play with it more tomorrow.  

Thanks a bunch!

**Comment by philippe44** [comment]
I had to modify the repository settings to have a proper sync between GitHub and SourceForge. Please go now at http://sourceforge.net/projects/lms-to-upnp/files/stable/repo-sf.xml for stable version and at http://sourceforge.net/projects/lms-to-upnp/files/dev/repo-sf.xml for development version.
I'm sorry for the inconvenience

**Comment by grtessman** [comment]
No worries, done.  Thank you!

Regards,
Gary Tessman
